name: MacOS Virtual Machine

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: MacOS Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setting Up the MacOS Environment
      env:
        CHROME_HEADLESS_CODE: ${{ secrets.CHROME_HEADLESS_CODE }}
      run: bash macos-run.sh "$CHROME_HEADLESS_CODE"

    - name: Keep Running MacOS System and keepAlive
      run: sleep 6h
